services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ../../models:/app/models
    environment:
      - MODEL_PATH=/app/models/cifar10_model.h5
  app:
    build: ./app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - api
